import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import { Button, Grid, Card, Text, Row, Container } from "@nextui-org/react";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [count, setCount] = useState(0);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.center}>
          <h2 className={styles.title}>
            Follow your facorite blogs and social media accounts from one place.
          </h2>
        </div>
        <Container justify="center" alignItems="center">
          <Grid sm={12} md={5} direction="column">
            <Card variant="bordered" isPressable onClick={() => setCount(0)}>
              <Card.Body>
                <Text h1>{count}</Text>
              </Card.Body>
              <Grid xs>
                <Card.Footer>
                  <Row justify="space-between" gap={10}>
                    <Button size="sm" onClick={() => setCount(count + 1)}>
                      +
                    </Button>
                    <Button size="sm" onClick={() => setCount(count - 1)}>
                      -
                    </Button>
                  </Row>
                </Card.Footer>
              </Grid>
            </Card>
          </Grid>
        </Container>
      </main>
    </>
  );
}
